### ISSUE TITLE
Warp points cleanup process suddenly not working

### ISSUE THREAD

**Issue by nntoan** [mfaerevaag/wd#35] opened 2016-01-14 08:40 UTC
Hi there,
I don't know why would be happened. This issue happens on OS X only, 1-2 months till now.
You could try add a warp point on OS X, then execute
wd clean
You will see this damn program telling you that your previous warp point doesn't exists which in fact it is.

Please gimme a resolution.

**Comment by chrisarcand** [comment] 2016-01-15 19:12
Confirmed not working for me, either. I'm not particularly skilled at bash/shell but I'll try and add a test case later. Thanks for the great plugin.

@nntoan Please refrain from opening pull requests on open source projects immediately referring to it as 'this damn program', as well as 'Please gimme resolution' (the 'please' does not excuse it being a demand for free work).

**Comment by kigster** [comment] 2016-03-07 22:54
@mfaerevaag @chrisarcand 

On the subject of time and future development – I loved `wd` so much, that I decided I can't live without it even in BASH. So I wrote a ruby gem for it. Right now it's almost at feature parity, but as time permits I'll be adding more  :)

https://github.com/kigster/warp-dir

Thanks for the insipiration!

**Comment by mfaerevaag** [comment] 2016-03-29 14:05
Hi all! Very sorry for my late reply. I am currently using my time trailing the mountains of Norway, and will therefore not have time to check on it in the near future, unfortunately.

@kigster Awesome! I don't know if you have seen the ruby branch, but I had the same issue with `fish`, so went the same direction. I haven't made much fuzz about it, as i seems that `wd`'s popularity is due to its simplicity and use through the `oh-my-zsh` plugin.

**Comment by mfaerevaag** [comment] 2017-04-05 04:32
@chrisarcand do you still have this issue? As you said, a failing test would be very helpful

**Comment by mfaerevaag** [comment] 2017-04-06 02:13
Closing until I hear something

**Closed by mfaerevaag** 2017-04-06 02:13 UTC

**Comment by nntoan** [comment] 2017-04-06 08:54
@mfaerevaag @chrisarcand Sorry for my behaviour in the past, that was young and stupid me.
For your @mfaerevaag question, it's gone. In the latest oh-my-zsh version, the issue has disappeared.
