### ISSUE TITLE
Error occur when run wd

### ISSUE THREAD

**Issue by hiberabyss** [mfaerevaag/wd#50] opened 2017-11-02 01:37 UTC
After update to the latest oh-my-zsh, following errors will occur when run `wd` (wd commit is `2102d10896fe14e912ed6ed8075bb0ddd3a5bc6a`):

```
➜  plugins git:(master) wd blog
_alias_tips__preexec:14: command not found: grep
_alias_tips__preexec:19: command not found: python
/Users/hbliu/.zgen/robbyrussell/oh-my-zsh-master/plugins/wd/wd.sh:382: command not found: getopt
wd_print_usage:2: command not found: cat
```

**Comment by altschuler** [comment] 2017-11-02 07:29
Hi! This is most likely caused by the bug described here: https://github.com/mfaerevaag/wd/issues/17#issuecomment-341236875

There is a pending PR to oh-my-zsh that fixes this here https://github.com/robbyrussell/oh-my-zsh/pull/6383

**Comment by mfaerevaag** [comment] 2017-11-08 02:33
Merged! @hiberabyss could you try updating and see if the bug persists?

**Comment by hiberabyss** [comment] 2017-11-08 03:14
@mfaerevaag The bug was fixed after updating. Thanks!

**Closed** 2017-11-08 04:26 UTC
