### ISSUE TITLE
wd rm does not work

### ISSUE THREAD

**Issue by cor** [mfaerevaag/wd#86] opened 2020-07-23 15:14 UTC
When I try to remove a point using `wd rm`, it does not work:

```sh
~/D/Go ❯❯❯ wd rm
wd_remove:13: file exists: /var/folders/q0/k80c6w4s6nx3jlqhv7zn0y_80000gn/T//wd.DleAXB3j1I
 * Something bad happened! Sorry.
~/D/Go ❯❯❯
```

I've tried running `rm /var/folders/q0/k80c6w4s6nx3jlqhv7zn0y_80000gn/T//wd*` but it did not resolve the issue.

**Comment by mfaerevaag** [comment] 2020-08-05 08:58
Thanks for reporting!

What's your zsh and wd version?

**Comment by alpha-tango-kilo** [comment] 2020-08-09 16:12
Could be due to my multi-remove PR, @cor can you verify if the issue still occurs using the `multi-remove` branch of my `wd` fork?

See PR #88 for explainer, but TL;DR `wd rm` without arguments isn't working as intended on master currently

**Comment by alpha-tango-kilo** [comment] 2020-08-26 21:30
PR merged, closing this

**Closed by alpha-tango-kilo** 2020-08-26 21:30 UTC
Labels: bug
